---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizcontroller-deployment
  namespace: wiz-controller
  labels:
    app: wizcontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wizcontroller
  template:
    metadata:
      labels:
        app: wizcontroller
    spec:
      containers:
        - name: wizcontroller
          image: ghcr.io/mitchfen/wiz-controller:latest
          resources: 
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 250Mi
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: wizcontroller-service
  namespace: wiz-controller
spec:
  type: ClusterIP 
  selector:
    app: wizcontroller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
