name: Publish Container Image

on:
  push:
    branches:
      - main

concurrency:
  group: "publish-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: pwsh

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    env:
      imageName: ghcr.io/mitchfen/wiz-controller:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to ghcr.io
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build -t ${{ env.imageName }} .

      - name: Push image
        run: docker push ${{ env.imageName }} 

